//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Details
    {
        public int StudentId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int StaffId { get; set; }
    
        public virtual Staff_Details Staff_Details { get; set; }
    }
}
